-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.4
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: trailing-whitespace
        args:
        - --no-markdown-linebreak-ext
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.4
    hooks:
    -   id: remove-crlf
    -   id: remove-tabs
-   repo: git://github.com/pre-commit/mirrors-pylint
    sha: v1.7.2
    hooks:
    -   id: pylint
        args:
        - --rcfile=.pylintrc
        - --reports=no
        files: ^brain_dump/.+\.py$
-   repo: local
    hooks:
    -   id: py.test
        name: py.test
        language: system
        entry: sh -c py.test
        files: ''
